# docker-compose.yml

version: "3.9"

services:
  catalog-db:
    image: postgres:15-alpine
    container_name: catalog-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      - ./postgres/scripts/ddl.catalog.sql:/docker-entrypoint-initdb.d/01_catalog-ddl.sql
      - ./postgres/scripts/dml.catalog.sql:/docker-entrypoint-initdb.d/02_catalog-dml.sql
    networks:
      - catalog-net

  catalog-api:
    build: 
      context: ./api  # Specifies the directory where the Dockerfile and application code are located
    container_name: catalog-api
    ports:
      - "5100:5100"
    depends_on:
      - catalog-db
    networks:
      - catalog-net
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

networks:
  catalog-net:
    name: catalog-net
